version: '3.7'

services:
  uetctf-bot:
    build: .
    image: eruditus:latest
    container_name: uetctf-bot
    restart: unless-stopped
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - .data:/data/db
